apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigdata-toolbox-deployment
  labels:
    app: bigdata-toolbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bigdata-toolbox
  template:
    metadata:
      labels:
        app: bigdata-toolbox
    spec:
      containers:
      - name: bigdata-toolbox
        image: nafeej/bigdata-toolbox
        imagePullPolicy: Always
        ports:
        - containerPort: 80
