apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-deployment
  labels:
    app: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
      - name: spark
        image: bitnami/spark
        imagePullPolicy: Always
        ports:
        - containerPort: 80
