apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\power\Coding Projects\Docker\kompose.exe convert
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-service
  name: spark
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    io.kompose.service: spark
status:
  loadBalancer: {}
